### PR TITLE
SAML2 Auth upgrade (rolling signing)

### PR DESCRIPTION
**Pull request by pet1330**
This has been tested using the SSM system but needs testing here against UoL IDP.

This update supports multiple signings so that when the University update their certificate it does not break or cause an interruption to service.

### CODE REVIEW

**Comment by pet1330** [comment]
Let me know when you have time and I'll talk you through the changes in the .env file and what you need to do to get it working :smiley:

**Comment by marc-hanheide** [comment]
Just looked at this and it seems to contain more changes, in particular, the frontend build seems to have been removed from the `Dockerfile`. Is this intended?
What are the new steps to do the front end build @pet1330 ?

**Comment by pet1330** [comment]
Ah, I've just realised that the entire application isn't mounted as a volume. I tend to mount the entire application and then run yarn and composer during deployment rather than during the build. They are then persisted between containers. I'm not sure which way is better to be honest, probably as it is, for now, lets revert it...

**Comment by pet1330** [comment]
It helps if I actually remember to commit the biggest change :stuck_out_tongue_winking_eye:

**Pull request merged**
