### PR TITLE
Update Dockerised Branch to Master

### PR DESCRIPTION
**Pull request by pet1330**
I've reviewed the changes between the `dockerised` and `master` branch, and I do not believe we actually need a separate LCAS specific branch. Everything that was LCAS specific has now been converted to configuration variables which can be set during deployment.

If you agree, can we delete the `dockerised` branch and tag a release on the `master` branch and update the production deployment?

### CODE REVIEW

**Comment by pet1330** [comment]
There isn't one, I looked into it and the `.env` file is loaded by php after apache (or nginx), so there is no way to use that as a variable for the apache rewrite unless it is hard coded.

The issue is that this is a deployment specific change, that would probably best be handled by a continuous deployment script which alters a template file when the container starts (or something similar to that)

**Comment by pet1330** [comment]
There isn't one, I looked into it and the `.env` file is loaded by php after apache (or nginx), so there is no way to use that as a variable for the apache rewrite unless it is hard coded.

The issue is that this is a deployment specific change, that would probably best be handled by a continuous deployment script which alters a template file when the container starts (or something similar to that)

**Comment by pet1330** [comment]
There isn't one, I looked into it and the `.env` file is loaded by php after apache (or nginx), so there is no way to use that as a variable for the apache rewrite unless it is hard coded.

The issue is that this is a deployment specific change, that would probably best be handled by a continuous deployment script which alters a template file when the container starts (or something similar to that)

**Comment by marc-hanheide** [comment]
that's true, let's keep it as an issue

**Pull request merged**
