### PR TITLE
Test composer.json requirements

### PR DESCRIPTION
**Pull request by pet1330**
I've updated Travis to pull in both the most up to date dependencies and also the lowest stable dependence given the composer.json versions on both php7.3 and php 7.4. The lowest dependence seems to fail which means that the versions set in the composer.json file need to be updated.

But the good news is that it appears to work with php7.4 :stuck_out_tongue:

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Sorry, me being ignorant, but I don't fully understand ;-)

**Comment by pet1330** [comment]
So the composer.json file defines the ranges for each of the dependencies, so for example:

```json
  "laravel/framework": "^5.5"
```
actually allows 5.5.* to be installed. By default, it will install the highest available, but it should also be able to run on the lowest available i.e. `5.5.0` in this case.

So I've changed Travis tests to check two install types per PHP version, firstly it tries to install the latest dependencies within the composer.json allowed range and then it checks prefer-lowest installation for the defined min versions in composer.json.

It's not really a problem, just means that the composer.json file needs tightening up a bit :wrench: :smiley:

**Comment by marc-hanheide** [comment]
But how to find out which one?

**Comment by pet1330** [comment]
I don't know if there is an easy way, I think you'd have to go through the failed tests and find out why they're failing :confused:

**Comment by pet1330** [comment]
Alternatively, just allow the lowest tests to fail, but if they are at least run then we're aware of it as an issue to be solved :smiley:

**Pull request closed without merging**
